coverage:
  precision: 2
  round: down
  range: "70...100" # range for red-green gradient in visualizations

  status:
    project: no
    patch:
      default:
        enabled: yes
        # basic
        target: 100%  # we always want 100% coverage for new code
        threshold: null
        base: pr 
    changes:
      default:
        enabled: yes
        # basic
        base: pr 
comment:
  layout: "diff"
  behavior: default
  require_changes: false  # if true: only post the comment if coverage changes
  require_base: no        # [yes :: must have a base report to post]
  require_head: yes       # [yes :: must have a head report to post]
  branches: null
