type: container
get:
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/acquisition-list.json
          schema: !include ../schemas/output/acquisition-list.json
post:
  description: Create a acquisition
  body:
    application/json:
      example: !include ../examples/input/acquisition.json
      schema: !include ../schemas/input/acquisition.json
/{AcquisitionId}:
  type: container-item
  get:
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/acquisition.json
            schema: !include ../schemas/output/acquisition.json
  put:
    body:
      application/json:
        example: !include ../examples/input/acquisition-update.json
        schema: !include ../schemas/input/acquisition-update.json
  /tags:
    type: tags-append
    /{TagValue}:
      type: tags-list
  /packfile-start:
    type: packfile-start
  /packfile:
    type: packfile
  /packfile-end:
    type: packfile-end
  /files:
    type: file-list-upload
    /{FileName}:
      type: file-item
  /notes:
    type: notes-list
    /{NoteId}:
      type: notes-item
  /analyses:
    type: analyses-list
    /{AnalysisId}:
      type: analysis-item
      /files:
        type: analysis-files
        /{Filename}:
          type: analysis-files-create-ticket-filename
      /notes:
        type: analysis-notes-list
        /{NoteId}:
          type: analysis-notes-item
