description: Scitran Config in JS format
get:
  description:  Return public Scitran configuration information in javascript format
  responses:
    200:
      body:
        text/html:
          example: !include ../examples/scitran_config.js.txt
