description: Utility functions for devices
get:
  description: |
    List all devices.
    Requires login.
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/device-list.json
          schema: !include ../schemas/output/device-list.json
post:
  description: |
    Modify a device's interval, info or set errors.
    Will modify the device record of device making the request.
    Request must be drone request.
  body:
    application/json:
      example: !include ../examples/input/device-update.json
      schema: !include ../schemas/input/device.json
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "modified": "1"
            }

/self:
  description: Device status
  get:
    description: |
      Get device document for device making the request.
      Request must be a drone request.
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/device.json
            schema: !include ../schemas/output/device.json

/status:
  description: Device status
  get:
    description: |
      Get status for all known devices.
      ok - missing - error - unknown
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/device-status.json
            schema: !include ../schemas/output/device-status.json

/{DeviceId}:
  description: Perform actions with a specific device
  uriParameters:
    DeviceId:
      type: string
  get:
    description: Get device details
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/device.json
            schema: !include ../schemas/output/device.json
      404:
        description: DeviceId not found
