get:
  description: List all groups
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/groups-list.json
          schema: !include ../schemas/output/groups-list.json
post:
  is: [validates-json-body]
  description: Add a group
  body:
    application/json:
      example: !include ../examples/input/group.json
      schema: !include ../schemas/input/group-new.json
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/group-new.json
          schema: !include ../schemas/output/group-new.json
/{GroupId}:
  uriParameters:
    GroupId:
      type: string
      required: true
  get:
    description: Get group info
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/group.json
            schema: !include ../schemas/output/group.json
  put:
    is: [validates-json-body]
    description: Update group
    body:
      application/json:
        example: !include ../examples/input/group-update.json
        schema: !include ../schemas/input/group-update.json
  delete:
    description: Delete a group
    responses:
      200:
        body:
          application/json:
            example: |
              {"deleted": 1}
            schema: !include ../schemas/output/group-delete.json
  /permissions:
    type: container-item-list-property-append
    post:
      body:
        application/json:
          example: !include ../examples/input/group-add-permission.json
          schema: !include ../schemas/input/permission.json
    /{UserId}:
      type: container-item-list-property
      uriParameters:
        UserId:
          description: User which is granted the permission
      get:
        responses:
          200:
            body:
              application/json:
                example: !include ../examples/output/permission.json
                schema: !include ../schemas/output/permission.json
      put:
        description: Update a permission
        body:
          application/json:
            example: !include ../examples/input/permission-update.json
            schema: !include ../schemas/input/permission.json
  /tags:
    type: tags-append
    post:
      description: |
        Add a tag to a group.
        Progates changes to projects, sessions and acquisitions
    /{TagValue}:
      type: tags-list
  /projects:
    get:
      description: Get projects in a group
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/output/project-list.json
              schema: !include ../schemas/output/project-list.json
