description: Login
post:
  description: Scitran Authentication
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "success": true
            }
