description: Log Out
post:
  description: Remove authtokens for user
  responses:
    200:
      body:
        application/json:
          example: |
            {
              "auth_tokens_removed": 2
            }
