type: container
get:
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/session-list.json
          schema: !include ../schemas/output/session-list.json
post:
  description: Create a session
  body:
    application/json:
      example: !include ../examples/input/session.json
      schema: !include ../schemas/input/session.json
/{SessionId}:
  type: container-item
  get:
    responses:
      200:
        body:
          application/json:
            example: !include ../examples/output/session.json
            schema: !include ../schemas/output/session.json
  put:
    body:
      application/json:
        example: !include ../examples/input/session.json
        schema: !include ../schemas/input/session.json
  /jobs:
    get:
      description: Return any jobs that use inputs from this session
      queryParameters:
        states:
          type: string
          description: filter results by job state
        tags:
          type: string
          description: filter results by job tags
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/output/session-jobs.json
              schema: !include ../schemas/output/session-jobs.json
  /tags:
    type: tags-append
    /{TagValue}:
      type: tags-list
  /packfile-start:
    type: packfile-start
  /packfile:
    type: packfile
  /packfile-end:
    type: packfile-end
  /files:
    type: file-list-upload
    /{FileName}:
      type: file-item
  /notes:
    type: notes-list
    /{NoteId}:
      type: notes-item
  /acquisitions:
    get:
      description: List acquisitions in a session
      responses:
        200:
          body:
            application/json:
              example: !include ../examples/output/acquisition-list.json
              schema: !include ../schemas/output/acquisition-list.json
  /analyses:
    type: analyses-list
    post:
      description: |
        When query param "job" is "true", send JSON to create
        an analysis and job.  Otherwise, multipart/form-data
        to upload files and create an analysis.
      body:
        application/json:
          schema: !include ../schemas/input/analysis-job.json
          example: !include ../examples/input/analysis-job.json
      responses:
        200:
          body:
            application/json:
              schema: !include ../schemas/output/container-new.json
              example: !include ../examples/output/container-new.json
    /{AnalysisId}:
      type: analysis-item
      /files:
        type: analysis-files
        /{Filename}:
          type: analysis-files-create-ticket-filename
      /notes:
        type: analysis-notes-list
        /{NoteId}:
          type: analysis-notes-item
