description: Upload files by label
post:
  description: |
    Multipart form upload with N file fields, each with their desired filename.
    For technical reasons, no form field names can be repeated. Instead, use (file1, file2) and so forth.
    A non-file form field called "metadata" is also required, which must be a string containing JSON.
    See api/schemas/input/labelupload.json for the fromat of this metadata.
  body:
    multipart/form-data:
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/file_info_list.json
    402:
      description: Uploads must be from an authorized drone
