import json
import bson
import dateutil

from .. import base
from .. import config
from .. import util

log = config.log

EIGHTEEN_YEARS_IN_SEC = 568036800

class APIReportException(Exception):
    pass

class ReportHandler(base.RequestHandler):

    def __init__(self, request=None, response=None):
        super(ReportHandler, self).__init__(request, response)

    def get(self, report_type, **kwargs):
        log.debug('lksdjflkdsjlfkdsjlk')
        report = None
        if report_type == 'site':
            report = SiteReport()

        elif report_type == 'project':
            project_list = self.request.GET.getall('projects')
            if len(project_list) < 1:
                self.abort(400, 'List of projects requried for Project Report')

            report = ProjectReport(map(bson.ObjectId, project_list),
                                   start_date=dateutil.parser.parse(self.get_param('start_date')),
                                   end_date=dateutil.parser.parse(self.get_param('end_date')))

        else:
            # They should never even get this far because of filtering in api.py
            self.abort(400, 'The report type {} is not supported'.format(report_type))

        return report.build()


def _get_result(output):
    """
    Helper function for extracting mongo aggregation results

    Given the output of a mongo aggregation call, checks 'ok' field
    If not 1 or 'result' field does not exist, throws APIReportException
    """

    if output.get('ok', 0) is 1:
        output.get('result')
        if result is not None: return result

    raise APIReportException

class Report(object):
    def __init__(self):
        self.placeholder = None

    def build(self):
        """
        Build and return a json report
        """
        raise NotImplementedError()


class SiteReport(Report):
    """
    Report of statistics about the site, generated by Site Managers

    Report includes:
      - number of groups
      - number of projects per group
      - number of sessions per group
    """

    def build(self):
        report = {}

        groups = config.db.groups.find({})
        report['group_count'] = groups.count()
        report['groups'] = []

        for g in groups:
            group = {}
            group['name'] = g.get('name')

            project_ids = [p['_id'] for p in config.db.projects.find({'group': group['name']}, [])]
            group['project_count'] = len(project_ids)

            group['session_count'] = config.db.sessions.count({'project': {'$in': project_ids}})
            report['groups'].append(group)

        return report

class ProjectReport(Report):
    """
    Report of statistics about a list of projects, generated by
    Project Admins or Group Admins. Will only include a sessions
    created in date range (inclusive) when provided by the client.

    Report includes:
      - Project Name
      - Group Name
      - Project Admin(s)
      - Number of Sessions
      - Unique Subjects
      - Male Subjects
      - Female Subjects
      - Other Subjects
      - Subjects with sex type Other
      - Subjects under 18
      - Subjects over 18
    """

    def __init__(self, projects, start_date=None, end_date=None):
        """
        Initialize a Project Report

        :projects:      a list of project ObjectIds
        :start_date:    ISO formatted timestamp
        :end_date:      ISO formatted timestamp
        """

        super(ProjectReport, self).__init__()
        self.projects = projects
        self.start_date = start_date
        self.end_date = end_date

    def _base_query(self, pid):
        base_query = {'project': pid}

        if start_date is not None or end_date is not None:
            base_query['created'] = {}
        if start_date is not None:
            base_query['created']['$gte'] = start_date
        if end_date is not None:
            base_query['created']['$lte'] = end_date

        return base_query

    def build(self):
        report = {}
        report['projects'] = []

        projects = config.db.projects.find({'_id': {'$in': self.projects}})
        for p in projects:
            project = {}
            project['name'] = p.get('label')
            project['group_name'] = p.get('group')

            # Create list of project admins
            admins = []
            for perm in p.get('permissions', []):
                if perm.get('access') == 'admin':
                    admins.append(perm.get('_id'))
            admin_objs = config.db.users.find({'_id': {'$in': admins}})
            project['admins'] = map(lambda x: x.get('firstname','')+' '+x.get('lastname',''), admin_objs)

            base_query = self._base_query(p['id'])
            project['session_count'] = config.db.sessions.count(base_query)

            # Count subjects
            # Any stats on subjects require an aggregation to group by subject._id
            subject_q = base_query.deepcopy()
            subject_q['subject._id'] = {'$exists: True'}

            pipeline = [
                {'$match': subject_q},
                {'$group': {'_id': '$subject._id'}},
                {'$group': {'_id': 1, 'count': { '$sum': 1 }}}
            ]

            result = _get_result(config.db.command('aggregate', 'sessions', pipeline=pipeline))
            project['subjects_count'] = result.get('count', 0)


            # Count subjects by sex
            sex_q = subject_q.deepcopy()
            sex_q['subject.sex'] = {'$exists: True'}

            pipeline = [
                {'$match': sex_q},
                {'$group': {'_id': '$subject._id', 'sex': {'$first': '$subject.sex'}}},
                {'$group': {'_id': '$sex', 'count': {'$sum': 1}}}
            ]
            result = _get_result(config.db.command('aggregate', 'sessions', pipeline=pipeline))

            # project['males_count'] = result['result']
            # project['female_count'] = result['result']
            # project['other_count'] = result['result']


            # Count subjects by age group
            age_q = subject_q.deepcopy()
            age_q['subject.age'] = {'$exists: True'}

            pipeline = [
                {'$match': age_q},
                {'$group': {'_id': '$subject._id', 'age': { '$avg': '$subject.age'}}},
                {'$project': {'_id': 1, 'over_18': {'$gte': ['$age', 568036800]}}}
                {'$group': {'_id': 'over_18', 'count': { '$sum': 1 }}}
            ]
            result = _get_result(config.db.command('aggregate', 'sessions', pipeline=pipeline))

            # project['over_18_count'] = result
            # project['under_18_count'] = result


            report['projects'].append(project)

        return report
