#%RAML 0.8
title: SciTran
version: 1
baseUri: https://docker.local.flywheel.io:8443/api

traits:
    - validates-json-body:
        description: Validates incoming request body
        responses:
            400:
                description: |
                    JSON did not validate against schema for this endpoint

resourceTypes:
  - container: !include resourceTypes/container.raml
  - container-item: !include resourceTypes/container-item.raml
  - container-item-list-property: !include resourceTypes/container-item-list-property.raml
  - container-item-list-property-append: !include resourceTypes/container-item-list-property-append.raml
  - tags-list: !include resourceTypes/tags-list.raml
  - tags-append: !include resourceTypes/tags-append.raml
  - packfile-start: !include resourceTypes/packfile-start.raml
  - packfile: !include resourceTypes/packfile.raml
  - packfile-end: !include resourceTypes/packfile-end.raml
  - file-list-upload: !include resourceTypes/file-list-upload.raml
  - file-item: !include resourceTypes/file-item.raml
  - permissions-list: !include resourceTypes/permissions-list.raml
  - permissions-item: !include resourceTypes/permissions-item.raml
  - notes-list: !include resourceTypes/notes-list.raml
  - notes-item: !include resourceTypes/notes-item.raml
  - analyses-list: !include resourceTypes/analyses-list.raml
  - analysis-item: !include resourceTypes/analysis-item.raml
  - analysis-files: !include resourceTypes/analysis-files.raml
  - analysis-files-create-ticket-filename: !include resourceTypes/analysis-files-create-ticket-filename.raml
  - analysis-notes-list: !include resourceTypes/analysis-notes-list.raml
  - analysis-notes-item: !include resourceTypes/analysis-notes-item.raml

/login: !include resources/login.raml
/logout: !include resources/logout.raml
/download: !include resources/download.raml
/upload/label: !include resources/upload-by-label.raml
/upload/uid: !include resources/upload-by-uid.raml
/upload/uid-match: !include resources/upload-match-uid.raml
/clean-packfiles: !include resources/clean-packfiles.raml
/engine: !include resources/engine.raml
/config: !include resources/config.raml
/config.js: !include resources/config-js.raml
/version: !include resources/version.raml
/users: !include resources/users.raml
/jobs: !include resources/jobs.raml
/gears: !include resources/gears.raml
/devices: !include resources/devices.raml
/groups: !include resources/groups.raml
/collections: !include resources/collections.raml
/sessions: !include resources/sessions.raml
/acquisitions: !include resources/acquisitions.raml
/projects: !include resources/projects.raml
/report: !include resources/report.raml
/savesearch: !include resources/savesearch.raml
