get:
  description: |
    If "ticket" query param is included and not empty, download files.
    If "ticket" query param is included and empty, create a ticket for all files in the anlaysis
    If no "ticket" query param is included, server error 500
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/analysis-files-create-ticket.json
          schema: !include ../schemas/output/analysis-files-create-ticket.json
