post:
  is: [validates-json-body]
  description: Add a <<resourcePathName|!singularize>>
  body:
    application/json:
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/container-update.json
          schema: !include ../schemas/output/container-update.json
