post:
  description: Start a packfile upload
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/packfile-start.json
          schema: !include ../schemas/output/packfile-start.json
