post:
    description: Add a permission
    is: ["validates-json-body"]
    body:
      application/json:
        schema: !include ../schemas/input/permission.json
        example: !include ../examples/input/permission.json
    responses:
      200:
        body:
          application/json:
            schema: !include ../schemas/output/container-update.json
            example: !include ../examples/output/container-update.json
