type: container-item-list-property
uriParameters:
  TagValue:
    description: The tag to interact with
    type: string
get:
  responses:
    200:
      body:
        application/json:
          example: !include ../examples/output/tag.json
          schema: !include ../schemas/output/tag.json
put:
  body:
    application/json:
      example: !include ../examples/input/tag.json
      schema: !include ../schemas/input/tag.json
