type: container-item-list-property-append
post:
  description: |
    Add a tag to a group.
    Progates changes to projects, sessions and acquisitions
  body:
    application/json:
      example: !include ../examples/input/tag.json
      schema: !include ../schemas/input/tag.json
